import * as fs from "fs";
import * as prettier from "prettier";

import { ClassData } from "@app/reflection/dataInterfaces";

export const formatAndSave = async (
  baseDir: string,
  outFile: string,
  classes: ClassData[]
): Promise<void> => {
  const jsons = classes.map((c) => {
    const path = c.fqcn.replace(new RegExp("/" + c.name + "$"), "");
    const importStr = `new Promise((r) => void import("./${path}").then((imp) => r(imp.${c.name})))`;
    return `{
      fqcn: "${c.fqcn}",
      name: "${c.name}",
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
      ctor: ${c.constructorVisibility === "public" ? importStr : "null"},
      implementsInterfaces: ${JSON.stringify(c.implementsInterfaces)},
      extendsClass: ${c.extendsClass ? `"${c.extendsClass}"` : "null"},
      constructorVisibility: "${c.constructorVisibility}",
      constructorParameters: ${JSON.stringify(c.constructorParameters)},
    }`;
  });
  const json = `[${jsons.join(",")}]`;

  const dataType = `
    export interface ParameterData {
      name: string;
      type: string;
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    type Constructor = new (...args: any[]) => any;
    export interface ClassData {
      fqcn: string;
      name: string;
      ctor: Promise<Constructor> | null;
      implementsInterfaces: string[];
      extendsClass: string | null;
      constructorParameters: ParameterData[];
      constructorVisibility: "public" | "protected" | "private";
    }`;

  const warning =
    "// This file was autogenerated by aero-di. It is recommended to not change it";

  const contents = `${warning}\n${dataType}\n export const classesReflection: ClassData[] = ${json};`;

  const outPath = `${baseDir}/${outFile}`;
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call,@typescript-eslint/no-unsafe-assignment,@typescript-eslint/no-unsafe-member-access
  const prettierConfigOptions = await prettier.resolveConfig(outPath);

  if (prettierConfigOptions) {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
    prettierConfigOptions.parser = "typescript";
  }
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call,@typescript-eslint/no-unsafe-member-access,@typescript-eslint/no-unsafe-assignment
  const formatted = prettier.format(
    contents,
    prettierConfigOptions ?? {
      parser: "typescript",
    }
  );

  fs.writeFileSync(outPath, formatted);
};
